### PR TITLE
Fix codegen to work with v3 module, non GOPATH location

### PR DESCRIPTION
**Pull request by ebauman**
- mod to v3 with proper dir
- fixed generate-client.sh to work with v3 mod

### CODE REVIEW

**Comment by ebauman** [comment]
@jggoebel please test with the code generation and let me know.

**Comment by jggoebel** [comment]
I will tomorrow! Thank you!

btw what is up with the slack?

**Comment by ebauman** [comment]
I sent you an email about this - not sure if you got it?

**Comment by jggoebel** [comment]
Oh I have not gotten it.

**Pull request merged**
