### PR TITLE
remove vendor directory

### PR DESCRIPTION
**Pull request by hall**
**What this PR does / why we need it**:
This removes the `vendor` directory (and updates the `Dockerfile` to pull modules at build time). It's just too much code mucking up diffs that doesn't need to be there. 

For example, this PR is nearly impossible to grok with a ~160k line diff: https://github.com/hobbyfarm/gargantua/pull/42/
Over 98% of which is changes to the files under `vendor/`.

```
$ git diff --stat master course-object vendor/ | tail -n1
 836 files changed, 159695 insertions(+)
```
If someone has a better idea to avoid huge diffs, I'm all ears.

**Which issue(s) this PR fixes**:

### CODE REVIEW

**Comment by ebauman** [comment]
I've been thinking about this for a few days and I am still undecided. 
On one hand, I agree that committing the vendor directory does add a lot to certain commits.
However, I also think it could be worth having it committed if only to preserve buildability of a release at any given time. 

Are there options to limit what diffs github shows? e.g. something like. `.gitdiffignore` lol

**Comment by hall** [comment]
Yeah, I've been reading what I can to understand this a little better. I feel like I'm still missing something important; I know reliable builds and such are essential but it sounds like the go community has started to solve that problem with services like https://proxy.golang.org/. It also feels like committing `./node_modules` or `~/.m2/repository` which I haven't _seen_ anyone doing (but maybe gophers are just crazy :stuck_out_tongue_closed_eyes:).

I can't find anything that would make GitHub ignore files in a diff (probably doesn't make sense to do that anyway). I see that Rancher and k/k are vendoring their modules and the [gist](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/vendor.md#justifications-for-an-update) seems to be that updating the vendor directory should be a dedicated process. While I'm still not convinced, that probably makes more sense once we have dependency scanning and testing in place.

Let me try to rework the PR I referenced above to not touch the vendored files. Maybe that's where I went wrong.

**Comment by Oats87** [comment]
@hall I've talked with @luthermonson about this, and I think for now we should keep vendor in place.

**Comment by luthermonson** [comment]
@hall its an unfortunate but necessary evil for what we do and we basically always check in vendor. helps in CI because you can do -mod vendor and have a consistent build. i've seen projects burned by disappearing modules before and even changing uppercase to lowercase names. i prefer it, it's technically personal preference and i'd just like to tell you that it's not that bad to live with if you follow the practice we do which is to consistently check in all vendored and generated code separately from your actual code changes.

basically for me if I saw 31 commits in a PR i'd write you a comment telling you to squash all your actual code changes into 1 commit with a nice commit message and then a separate commit for ./vendor so i can ignore it and only check your real code changes. honestly, i agree with you about checking in node_modules or ./.m2/repository, youre not wrong but let me remind you of leftpad, maybe they should check them in. I've sort of come around on this problem, i used to be like you until i started doing go and building a ton more containers and now i dont like the extra overhead of cloning a repo AND downloading packages.

**Comment by hall** [comment]
OK, I think the separate check-in process helps (also probably helps if I don't just willy-nilly update all of the vendor code when opening a PR).

I hadn't heard of the leftpad incident before; pretty interesting and certainly makes me question how reliable dependency caches are. I guess for our use-case checking them in makes the most sense (seeing how we're not going to run our own cache or anything). Coincidentally, I was actually building a project last week when GitHub had a service outage so I have a recent appreciation of where you're coming from.

At any rate, thanks for the patient explanation. I think I just had to bicker a bit and then get over it :sweat_smile:

**Pull request closed without merging**
