### PR TITLE
convert to modules

### PR DESCRIPTION
**Pull request by hall**
**What this PR does / why we need it**:
I'm no go expert but I think these changes migrate dependencies to go modules.

**Which issue(s) this PR fixes**:

### CODE REVIEW

**Comment by luthermonson** [comment]
@hall delete ./vendor and run `go mod tidy` and `go mod vendor` and check in any changes from that and you should be good.

**Comment by hall** [comment]
Thanks @luthermonson! I've done just that :100:

**Comment by Oats87** [comment]
@luthermonson @hall should we keep `vendor` in place?

**Comment by luthermonson** [comment]
@Oats87 yup!

**Pull request merged**
