### PR TITLE
WIP Update onboarding material and CI/PKG pipelines

### PR DESCRIPTION
**Pull request by devpro**
## What this PR does / why we need it

As someone new to HobbyFarm project, I would like to use my fresh new eyes to try to ease the onboarding of a newcomer, improve the way the software cycle automation works (pipelines) and follow best practices (removed old files that are not needed, simplify procedures, add quality checks).

## Which issue(s) this PR fixes

- Split pipeline (GitHub Action) into dedicated CI & PKG pipelines to take advantage of a full CI for Pull Requests, simplify actions and do not mix Continuous Integration and Continuous Delivery objectives
- Fix typo Markdown files and add documentation content
- Remove useless files (Rancher pipeline, empty files)

### CODE REVIEW

**Comment by jggoebel** [comment]
removing `cicd/Dockerfile` will result in longer Pipeline runs (twice as long)

We use the cicd/Dockerfile to make use of go module caching in the CI. We build gargantua using the pipeline and then repackage it in docker. The Dockerfile under / uses a second container for building go, which is slower (No caching) but can be used for building gargantua locally.
Currently this PR introduces the CI workflow which builds gargantua with go and then builds it again in docker via the dockerfile.

**Comment by devpro** [comment]
> removing `cicd/Dockerfile` will result in longer Pipeline runs (twice as long)
> 
> We use the cicd/Dockerfile to make use of go module caching in the CI. We build gargantua using the pipeline and then repackage it in docker. The Dockerfile under / uses a second container for building go, which is slower (No caching) but can be used for building gargantua locally. Currently this PR introduces the CI workflow which builds gargantua with go and then builds it again in docker via the dockerfile.

Thank you for the confirmation! I understand the how it's interesting. But I don't think it's the way to do it "by the book", the go build should be made in the same system as the Docker file base image (system). If for example the pipeline runs on Linux system A and the Dockerfile base is using system B we could have strange behavior in the image generated and also no easy way to generate again if needed (we can't tag the GitHub Action base image). I think the gain (few seconds) doesn't worth the risk but I will rollback it for the CI pipeline it's better.

**Comment by ebauman** [comment]
We should clean this up for merge

**Comment by devpro** [comment]
Wasn't able to complete the work and moving on another platform (from having no response on Slack channel).

**Pull request closed without merging**
